### ISSUE TITLE
Error inserting module on linux 6.0.6

### ISSUE THREAD

**Issue by c-nixon** [landhb/DrawBridge#31]
I get the following error in dmesg while trying out drawbridge from the latest master (commit 99376d4aea) on Arch Linux using the distro provided 6.0.6 package.

Command:

```bash
insmod drawbridge.ko ports=22,445 
```

dmesg output:

```
[-] Could not attach bpf zero filter to socket -12 
[-] drawbridge: Unable to setup child thread
```

I added a few printk's and it seems like the failure is coming from the [refcount check](https://github.com/landhb/DrawBridge/blob/99376d4aeaeba972c2ac82b8eebd6c05fd8d3bdb/module/src/sk_filter.c#L101) in `db_sk_filter_charge`.

Is there anything I can do to help debug?

**Comment by landhb** [comment]
@c-nixon Thanks for the report.

Just curious, what value to you have for:

`sysctl net.core.optmem_max`

Since that's the value that ends up checked here:

https://github.com/landhb/DrawBridge/blob/master/module/src/sk_filter.c#L70

More information on the configuration value:

https://stackoverflow.com/questions/47723793/in-linux-how-do-i-determine-optimal-value-of-optmem-max

If increasing that value doesn't work we could try running under gdb with nixmodule to see where it's failing.

**Comment by landhb** [comment]
Didn't have my coffee this morning, just noticing you said it was from the `refcount_inc_not_zero`. That is more confusing haha. I'll try to take a look
